[Icon Theme]
Name=HoloNight
Comment=Dark Linux icon theme with selected overrides for Papirus-Dark
Inherits=Papirus-Dark,Papirus,breeze-dark,hicolor
FollowsColorScheme=true


Directories=16x16/panel,16x16/places,16x16@2x/panel,16x16@2x/places,22x22/panel,22x22/places,22x22@2x/panel,22x22@2x/places,24x24/panel,24x24/places,24x24@2x/panel,24x24@2x/places,32x32/panel,32x32/places,32x32@2x/panel,32x32@2x/places,48x48/places,48x48@2x/places,64x64/panel,64x64/places,64x64@2x/panel,64x64@2x/places,96x96/places,128x128/places,scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/mimetypes,scalable/places,scalable/status,symbolic/actions,symbolic/status,symbolic/devices,symbolic/places

[16x16/panel]
Context=Status
Size=16
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[16x16@2x/panel]
Context=Status
Size=16
Type=Fixed
Scale=2

[16x16@2x/places]
Context=Places
Size=16
Type=Fixed
Scale=2

[22x22/panel]
Context=Status
Size=22
Type=Fixed

[22x22/places]
Context=Places
Size=22
Type=Fixed

[22x22@2x/panel]
Context=Status
Size=22
Type=Fixed
Scale=2

[22x22@2x/places]
Context=Places
Size=22
Type=Fixed
Scale=2

[24x24/panel]
Context=Status
Size=24
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[24x24@2x/panel]
Context=Status
Size=24
Type=Fixed
Scale=2

[24x24@2x/places]
Context=Places
Size=24
Type=Fixed
Scale=2

[32x32/panel]
Context=Status
Size=32
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[32x32@2x/panel]
Context=Status
Size=32
Type=Fixed
Scale=2

[32x32@2x/places]
Context=Places
Size=32
Type=Fixed
Scale=2

[48x48/places]
Context=Places
Size=48
Type=Fixed

[48x48@2x/places]
Context=Places
Size=48
Type=Fixed
Scale=2

[64x64/panel]
Context=Status
Size=64
Type=Fixed

[64x64/places]
Context=Places
Size=64
Type=Fixed

[64x64@2x/panel]
Context=Status
Size=64
Type=Fixed
Scale=2

[64x64@2x/places]
Context=Places
Size=64
Type=Fixed
Scale=2

[96x96/places]
Context=Places
Size=96
Type=Fixed

[128x128/places]
Context=Places
Size=128
Type=Fixed

[scalable/actions]
Context=Actions
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/apps]
Context=Applications
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/categories]
Context=Categories
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/devices]
Context=Devices
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Context=MimeTypes
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/places]
Context=Places
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Context=Status
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/actions]
Context=Actions
Size=16
Type=Scalable
MinSize=16
MaxSize=32

[symbolic/status]
Context=Status
Size=16
Type=Scalable
MinSize=16
MaxSize=32

[symbolic/devices]
Context=Devices
Size=16
Type=Scalable
MinSize=16
MaxSize=32

[symbolic/places]
Context=Places
Size=16
Type=Scalable
MinSize=16
MaxSize=32
